/** Roteiro de apresentação do Laboratório SQL. Usado pela tela e pelo teste automático (scripts/test-sql-lab.mjs). */
export type Level = "Buscas" | "Análises" | "Cruzando tabelas" | "Doações" | "Tente quebrar";
export type Step = { level: Level; title: string; say: string; shows: string; query: string; blocked?: boolean };
export const steps: Step[] = [
  { level: "Buscas", title: "Quem está em análise?", say: "Uma busca simples. O WHERE escolhe as linhas e o ORDER BY coloca em ordem alfabética.", shows: "WHERE · ORDER BY", query: "SELECT name, niche, stage FROM volunteers WHERE status = 'Em análise' ORDER BY name LIMIT 50" },
  { level: "Buscas", title: "Música ou cabelo", say: "É a mesma busca do assistente de voluntários. O LIKE com % procura um pedaço do texto e o OR junta os dois assuntos.", shows: "LIKE · OR", query: "SELECT name, niche, city FROM volunteers WHERE niche_key LIKE '%musica%' OR niche_key LIKE '%cabelo%' ORDER BY name LIMIT 50" },
  { level: "Buscas", title: "Fichas incompletas", say: "Mostra quem está sem e-mail, telefone ou cidade. Serve para a equipe corrigir cadastros antes de uma ação.", shows: "Qualidade dos dados", query: "SELECT name, email, phone, city FROM volunteers WHERE email = '' OR phone = '' OR city = '' ORDER BY name LIMIT 50" },
  { level: "Análises", title: "Voluntários por área", say: "O GROUP BY junta as pessoas da mesma área e o COUNT conta cada grupo. É a base de qualquer gráfico de barras.", shows: "GROUP BY · COUNT", query: "SELECT niche, COUNT(*) AS total FROM volunteers GROUP BY niche ORDER BY total DESC LIMIT 30" },
  { level: "Análises", title: "Situação × etapa", say: "Agrupar por duas colunas cria uma tabela de contagens, parecida com uma tabela dinâmica do Excel.", shows: "GROUP BY com 2 colunas", query: "SELECT status, stage, COUNT(*) AS total FROM volunteers GROUP BY status, stage ORDER BY total DESC LIMIT 50" },
  { level: "Análises", title: "Áreas com 2 ou mais pessoas", say: "O WHERE filtra linhas antes de contar. O HAVING filtra os grupos depois de contar.", shows: "HAVING", query: "SELECT niche, COUNT(*) AS total FROM volunteers GROUP BY niche HAVING total >= 2 ORDER BY total DESC LIMIT 30" },
  { level: "Análises", title: "Total de pessoas", say: "Um único número para o painel: quantas fichas existem nesta sessão.", shows: "COUNT(*)", query: "SELECT COUNT(*) AS total FROM volunteers" },
  { level: "Cruzando tabelas", title: "Ações com o nome do parceiro", say: "A ação guarda só o número do parceiro. O JOIN liga as duas tabelas e traz o nome. O LEFT JOIN mantém a ação mesmo sem parceiro.", shows: "LEFT JOIN", query: "SELECT a.title, p.name AS parceiro, a.status, a.participants FROM actions a LEFT JOIN partners p ON p.id = a.partner_id ORDER BY a.scheduled_at DESC LIMIT 50" },
  { level: "Cruzando tabelas", title: "Participantes por situação da ação", say: "SUM soma uma coluna numérica. Aqui vemos quantas ações e quantos participantes há em cada etapa do fluxo.", shows: "SUM · GROUP BY", query: "SELECT status, COUNT(*) AS acoes, SUM(participants) AS participantes FROM actions GROUP BY status ORDER BY participantes DESC LIMIT 20" },
  { level: "Cruzando tabelas", title: "Média de participantes por parceiro", say: "Junta ações e parceiros e calcula a média com AVG. Responde: qual parceiro costuma trazer mais gente?", shows: "AVG · JOIN · GROUP BY", query: "SELECT p.name AS parceiro, COUNT(*) AS acoes, AVG(a.participants) AS media FROM actions a JOIN partners p ON p.id = a.partner_id GROUP BY p.name ORDER BY media DESC LIMIT 20" },
  { level: "Doações", title: "Saldo de cada lote", say: "O banco calcula na hora: recebido menos distribuído. O saldo nunca fica negativo porque o sistema bloqueia saídas acima do lote.", shows: "Cálculo entre colunas", query: "SELECT item, donor, quantity_received - quantity_distributed AS saldo FROM donations ORDER BY saldo DESC LIMIT 20" },
  { level: "Doações", title: "Rastreio: do lote ao destino", say: "Cada entrada e saída fica registrada. O JOIN mostra qual item se moveu, quanto e para onde.", shows: "JOIN · rastreabilidade", query: "SELECT d.item, m.kind, m.quantity, m.destination FROM donation_movements m JOIN donations d ON d.id = m.donation_id ORDER BY m.created_at LIMIT 50" },
  { level: "Doações", title: "Total distribuído por destino", say: "Filtra só as saídas e soma por destino. É o tipo de resposta que o setor precisa para prestar contas.", shows: "SUM · WHERE · GROUP BY", query: "SELECT destination, SUM(quantity) AS total FROM donation_movements WHERE kind = 'Saída' GROUP BY destination LIMIT 20" },
  { level: "Tente quebrar", title: "Apagar uma tabela", say: "Tente destruir os dados. O laboratório só aceita SELECT, então o comando é recusado antes de chegar ao banco.", shows: "Somente leitura", query: "DROP TABLE volunteers", blocked: true },
  { level: "Tente quebrar", title: "Segundo comando escondido", say: "Um ataque clássico: encerrar a consulta com ; e colar outro comando. Ponto e vírgula não é aceito.", shows: "Uma instrução por vez", query: "SELECT name FROM volunteers; DELETE FROM volunteers", blocked: true },
  { level: "Tente quebrar", title: "Pegadinha do 1=1", say: "Outra injeção famosa, que tenta fazer o filtro valer para todas as linhas. O servidor só aceita comparar uma coluna com um valor.", shows: "Injeção de SQL", query: "SELECT name FROM volunteers WHERE status = 'x' OR 1=1", blocked: true },
  { level: "Tente quebrar", title: "Espiar uma tabela interna", say: "Só as tabelas do dicionário de dados estão liberadas. Sessões de login e fila do chat ficam fora.", shows: "Lista de permissões", query: "SELECT token FROM staff_sessions", blocked: true },
  { level: "Tente quebrar", title: "Ver dados de outra sessão", say: "A coluna owner identifica quem é dono de cada linha. Ela não pode ser lida nem filtrada, e o servidor sempre acrescenta o filtro da sua sessão.", shows: "Isolamento por sessão", query: "SELECT owner FROM volunteers", blocked: true },
];
export const levels: Level[] = ["Buscas", "Análises", "Cruzando tabelas", "Doações", "Tente quebrar"];

